# Generated by Django 2.1.7 on 2019-05-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='pictureUrl',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
