# Generated by Django 2.1.7 on 2019-05-11 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaPelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('idPelicula', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('fechaDeEstreno', models.DateTimeField()),
                ('imdbURL', models.URLField()),
                ('categorias', models.ManyToManyField(through='principal.CategoriaPelicula', to='principal.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('idPelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('codigoPostal', models.IntegerField()),
                ('ocupacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Ocupacion')),
            ],
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Usuario'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='puntuaciones',
            field=models.ManyToManyField(through='principal.Puntuacion', to='principal.Usuario'),
        ),
        migrations.AddField(
            model_name='categoriapelicula',
            name='idPelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Pelicula'),
        ),
    ]
