# Generated by Django 2.1.7 on 2019-05-07 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_receta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.TextField()),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('genero', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('peliculaID', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('imbdID', models.IntegerField()),
                ('thdbID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateTimeField()),
                ('peliculaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuarioID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='puntuacion',
            name='usuarioID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Usuario'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='etiquetas',
            field=models.ManyToManyField(related_name='etiquetas', through='principal.Etiqueta', to='principal.Usuario'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='generos',
            field=models.ManyToManyField(to='principal.Genero'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='puntuaciones',
            field=models.ManyToManyField(through='principal.Puntuacion', to='principal.Usuario'),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='peliculaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Pelicula'),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='usuarioID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Usuario'),
        ),
    ]
