# Generated by Django 2.1.7 on 2019-05-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20190509_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='tmbdID',
            new_name='tmdbID',
        ),
    ]
