# Generated by Django 2.1.7 on 2019-05-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20190509_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='tmdbID',
            field=models.IntegerField(blank=True),
        ),
    ]
