# Generated by Django 2.1.7 on 2019-05-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20190510_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='tmdbID',
            field=models.IntegerField(null=True),
        ),
    ]
