# Generated by Django 2.1.7 on 2019-05-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20190510_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bebida',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
    ]
