# Generated by Django 2.1.7 on 2019-05-22 19:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('school', models.CharField(max_length=20)),
                ('castingTime', models.CharField(max_length=20)),
                ('components', models.CharField(max_length=40)),
                ('duration', models.CharField(max_length=20)),
                ('range', models.CharField(max_length=30)),
                ('hasRitual', models.BooleanField()),
                ('requireConcentration', models.BooleanField()),
                ('description', models.TextField()),
                ('source', models.TextField()),
                ('classCharacter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fromClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Class')),
            ],
        ),
        migrations.AddField(
            model_name='spell',
            name='subclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subclass'),
        ),
        migrations.AddField(
            model_name='character',
            name='classCharacter',
            field=models.ForeignKey(default='mage', on_delete=django.db.models.deletion.CASCADE, to='main.Class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(default='tiefling', on_delete=django.db.models.deletion.CASCADE, to='main.Race'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(to='main.Spell'),
        ),
        migrations.AddField(
            model_name='character',
            name='subclass',
            field=models.ForeignKey(default='bomberman', on_delete=django.db.models.deletion.CASCADE, to='main.Subclass'),
            preserve_default=False,
        ),
    ]
