# Generated by Django 2.1.7 on 2019-05-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190530_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='source',
        ),
    ]
