# Generated by Django 2.1.7 on 2019-05-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_spell_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='classCharacter',
            new_name='classes',
        ),
        migrations.RenameField(
            model_name='spell',
            old_name='subclass',
            new_name='subclasses',
        ),
    ]
