# Generated by Django 2.1.7 on 2019-05-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_character_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='type',
            field=models.CharField(choices=[('Damage', 'Damage'), ('Healing', 'Healing'), ('Utility', 'Utility')], default='damage', max_length=10),
            preserve_default=False,
        ),
    ]
